# Task 3.1

In [4]:
import numpy as np

In [13]:
massive = np.ndarray(shape = (3, 4, 2))

In [14]:
list_1 = [[1, 2], [3, 4], [5, 6], [7, 8]]
list_2 = [[9, 10], [11, 12], [13, 14], [15, 16]]
list_3 = [[17, 18], [19, 20], [21, 22], [23, 24]]
arr = np.array([list_1, list_2 , list_3])

print arr, arr.shape

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]] (3L, 4L, 2L)


In [17]:
mas = np.random.rand(3,4,2)

Теперь продемонстрируем как обращаться к элементам ndarray.

In [18]:
arr[0,3,1]

8

Выведем определенные контейнеры из нашего ndarray

In [19]:
arr[0:2]

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [20]:
arr[xrange(2,3)]

array([[[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

Выведем во всех матрицах элемент второй строки и второго столбца.

In [21]:
arr[...,1,1]

array([ 4, 12, 20])

Выведем все вторые столбцы в каждой матрице нашего трехмерного ndarray.

In [22]:
arr[...,1]

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

Выведем в кажой матрице элементы первой строки и первого столбца

In [23]:
arr[[0, 1, 2], [0, 0 , 0], [0, 0, 0]]

array([ 1,  9, 17])

Выведем в первой и последней матрице элементы первой строки

In [24]:
arr[[0, 2], [0, 0 ]]


array([[ 1,  2],
       [17, 18]])

In [25]:
arr[1,:,1]

array([10, 12, 14, 16])

# Task 3.2

In [26]:
array = np.random.rand(100,10,10)

In [27]:
list1 = array.tolist()
mylist = reduce(lambda x, a: x + a, reduce(lambda x, a: x + a, list1))

In [28]:
def sum_for_time(array):
    sum_ = 0
    if type(array) == np.ndarray:
        for i in xrange(1,10000):
            sum_ = sum_ + array.sum()
    
    if type(array) == type([]):
        for i in xrange(1,10000):
            sum_ = sum_ + sum(array)
      
    return sum_   

% time sum_for_time(array)

Wall time: 111 ms


50052621.543328077

In [29]:
% time sum_for_time(mylist)


Wall time: 663 ms


50052621.543328084

Видим, что время работы с ndarray больше чем с list

# Task 3.3

In [30]:
a = 1
b = 10
num = 10000000
step = (b - a)/float(num - 1)

x = np.linspace(a, b, num = num)
% time x.sum()

Wall time: 12 ms


54999999.99999997

In [31]:
y = [x for x in np.arange(a, b , step)]
y.append(b)

% time sum(y)

Wall time: 1.2 s


55000000.000472352